### PR TITLE
Add Paris event

### PR DESCRIPTION
**Pull request by thedevelopnik**
* Puts the Chicago event back into draft mode to remove it from the main page.
* Adds Paris event with registration form included.

### CODE REVIEW

**Review by PiMastah — COMMENTED** [review]
Do we have permission to use all the images? Especially the AWS image. Also, the AWS image seems to be way bigger than the other images.

I can't speak to the validity of the claims made in the text regarding location and setup there with health items, but since this is more or less copied from earlier events it is worth double checking that the claims we make are actually true.

Regarding the stated use of emails I believe we need to inform attendees about the intended use of the emails. I don't think we can claim that emails will not be shared, as we will share parts of emails. IMO the current text suggests we do no sharing at all which - in my view - is not factually correct.

**Comment by mocdaniel** [comment]
> Also, the AWS image seems to be way bigger than the other images.

Can confirm. We should try to get our hands on an AWS graphic with a better width/height ratio as Hugo will scale them automatically.

TestifySec's logo having a solid white background is unfortunate, too. It shows when the sponsors section overlaps with the fading background while scrolling down.

**Comment by thedevelopnik** [comment]
Yeah, those two in particular were placeholders. I'll ask Farrah from AWS and Matt from TestifySec for better ones. Just wanted to get the page up, but we can hold on publishing it until I get those images.

**Comment by thedevelopnik** [comment]
@PiMastah yeah good point about the emails, I will update the copy. Thank you!

As a draft on the health regulations, I took out the sentence saying masks and hand sanitizer are available, and "due to local laws and regulations" about proof of vaccination. But also asked for input in the Discord.

**Comment by thedevelopnik** [comment]
@PiMastah @mocdaniel I think this is ready for final review!

**Comment by thedevelopnik** [comment]
@mocdaniel @PiMastah ok actually last issue, I had thought I could cut the AWS logo down to the smile, but I can't. So it'll be square, which will cause it to be big...not sure what to do about that.

**Comment by thedevelopnik** [comment]
Maybe I can forcibly move it into a background that is wider.

**Review by PiMastah — APPROVED** [review]
LGTM now

**Comment by thedevelopnik** [comment]
Added the registration form! Should be ready for merge now.

**Pull request merged**
